services:
  postgres:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: user_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d user_db"]
      start_period: 2.5s
      interval: 2.5s
      timeout: 15s
      retries: 5

  user-service:
    build:
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port ${USER_SERVICE_PORT} --reload
    environment:
      - DATABASE_URL=${USER_DB_URL}
      - PYTHONPATH=/
    env_file:
      - .env
    volumes:
      - ${USER_SERVICE_PATH}/app:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - web
      - postgres

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - web

networks:
  postgres:
  web:

volumes:
  postgres_data:
