[project]
name = "generic-user-service"
version = "0.1.0"
description = "Generic user service for authn and authz"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "litestar[standard]>=2.16.0",
]
